# Generated by Django 4.1.5 on 2023-03-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='bank_code',
            field=models.CharField(choices=[('044', 'Access Bank'), ('023', 'Citibank'), ('050', 'Ecobank'), ('214', 'FCMB'), ('070', 'Fidelity'), ('011', 'First Bank'), ('058', 'GTB'), ('030', 'Heritage'), ('301', 'Jaiz Bank'), ('082', 'Keystone'), ('526', 'Parallex'), ('101', 'Providus'), ('221', 'Stanbic'), ('076', 'Skye Bank'), ('068', 'Standard Bank'), ('232', 'Sterling Bank'), ('100', 'Suntrust Bank'), ('102', 'Titan Trust'), ('032', 'Union Bank'), ('033', 'United Bank'), ('215', 'Unity Bank'), ('035', 'Wema Bank'), ('057', 'Zenith Bank')], max_length=400, null=True),
        ),
    ]
