# Generated by Django 4.1.5 on 2023-03-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_organizer_bank_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='account_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
